version: 2

jobs:
  build:
    docker:
      - image: circleci/buildpack-deps

      - image: circleci/mysql:5.7
        environment:
          MYSQL_DATABASE: exampledb
          MYSQL_USER: exampleuser
          MYSQL_PASSWORD: examplepass
          MYSQL_RANDOM_ROOT_PASSWORD: '1'

    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: start MySQL
          command: |
            docker run -d --name wpdb \
            -e MYSQL_DATABASE=exampledb \
            -e MYSQL_USER=exampleuser \
            -e MYSQL_PASSWORD=examplepass \
            -e MYSQL_RANDOM_ROOT_PASSWORD='1'
            mysql:5.7

      - run:
          name: wait for DB
          command: dockerize -wait tcp://localhost:3306 -timeout 1m
      - run:
          name: start WordPress
          command: |
            docker run -d --name some-wordpress \
            -e WORDPRESS_DB_HOST=127.0.0.1 \
            -e WORDPRESS_DB_USER=exampleuser \
            -e WORDPRESS_DB_PASSWORD=examplepass \
            -e WORDPRESS_DB_NAME=exampledb \
            -p 8080:80 \
            wordpress

      - run:
          name: download, config, and install WordPress
          command: |
            docker run -it --rm \
            --volumes-from some-wordpress \
            #--network container:some-wordpress \
            wordpress:cli core install --url=localhost --title=test --admin_user=test --admin_password=test --admin_email=test@example.com --allow-root --path=/var/www/html
