version: 2

jobs:
  build:
    docker:
      - image: circleci/buildpack-deps

    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Set up network
          command: docker network create wp-network
      - run:
          name: start MySQL
          command: |
            docker run -d --name wpdb \
            -e MYSQL_ROOT_PASSWORD=1234 \
            -e MYSQL_DATABASE=wordpress \
            --name db \
            --network wp-network \
            mysql:5.7

      - run:
          name: setup WordPress config
          command: |
            docker run -d \
            -e WORDPRESS_DB_HOST=db:3306 \
            -e WORDPRESS_DB_USER=root \
            -e WORDPRESS_DB_PASSWORD=1234 \
            -e WORDPRESS_DB_NAME=wordpress \
            --name wp-container \
            --network wp-network \
            wordpress

      # - run:
      #     name: wait for DB
      #     command: dockerize -wait tcp://localhost:3306 -timeout 1m

      - run:
          name: install WordPress
          command: |
            docker run -it --rm \
            --volumes-from wordpress \
            --network wp-network \
            wordpress:cli core install --url=localhost --title=test --admin_user=test --admin_password=test --admin_email=test@example.com --allow-root --path=/var/www/html
