version: 2

jobs:
  build:
    docker:
      - image: wordpress:cli

      - image: wordpress
        environment:
          WORDPRESS_DB_HOST: localhost:3306
          WORDPRESS_DB_USER: root
          WORDPRESS_DB_PASSWORD: 1234
          WORDPRESS_DB_NAME: wordpress

      - image: circleci/mysql:5.7
        environment:
          MYSQL_ROOT_PASSWORD: 1234
          MYSQL_DATABASE: wordpress

    steps:
      - checkout
      - run:
          name: install WordPress
          command: |
            wp core install --url=localhost --title=test --admin_user=test --admin_password=test --admin_email=test@example.com --allow-root --path=/var/www/html
