version: 2

jobs:
  build:
    docker:
      - image: circleci/buildpack-deps
      # - image: wordpress
      #   environment:
      #     WORDPRESS_DB_HOST: localhost
      #     WORDPRESS_DB_USER: exampleuser
      #     WORDPRESS_DB_PASSWORD: examplepass
      #     WORDPRESS_DB_NAME: exampledb

      - image: circleci/mysql:5.7
        environment:
          MYSQL_DATABASE: exampledb
          MYSQL_USER: exampleuser
          MYSQL_PASSWORD: examplepass
          MYSQL_RANDOM_ROOT_PASSWORD: '1'

      # - image: wordpress:cli

    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: wait for DB
          command: dockerize -wait tcp://localhost:3306 -timeout 1m
      - run:
          name: start WordPress
          command: |
            docker run -d --name some-wordpress \
            -e WORDPRESS_DB_HOST=localhost \
            -e WORDPRESS_DB_USER=exampleuser \
            -e WORDPRESS_DB_PASSWORD=examplepass \
            -e WORDPRESS_DB_NAME=exampledb \
            -p 8080:80 \
            wordpress

      - run:
          name: download, config, and install WordPress
          command: |
            docker run -it --rm \
            --volumes-from some-wordpress \
            --network container:some-wordpress \
            wordpress:cli core install --url=localhost --title=test --admin_user=test --admin_password=test --admin_email=test@example.com --allow-root --path=/var/www/html
